export const metadata = {
  title: "About",
  description: "About - Generated by create next app",
};

const About = () => {
  return (
    <div className="mt-10">
      {/* text-white drop-shadow-[5px_5px_green] */}
      <h2
        className="text-disney"
        style={{}}
      >
        Disney
      </h2>
      <svg viewBox="0 0 450 70">
        <text
          className="svgText"
          x="10"
          y="45"
        >
          bluuweb
        </text>
      </svg>
    </div>
  );
};
export default About;
